spring.application.name=settleup
spring.datasource.url=jdbc:postgresql://localhost:5432/settleup
spring.datasource.username=postgres
spring.datasource.password=abc@123
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=change-this-to-a-long-random-secret-key-at-least-32-characters-long
jwt.expiration-ms=86400000