spring.application.name=settleup
spring.datasource.url=jdbc:postgresql://localhost:5432/settleup
spring.datasource.username=postgres
spring.datasource.password=abc@123
spring.datasource.driver-class-name=org.postgresql.Driver
